# Generated by Django 2.2 on 2021-08-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiadas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
